version: "3.9"

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    env_file:
      - .env
    ports:
      - 5432:5432