apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: btd
spec:
  selector:
    app: postgres
    tier: backend
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 5432
      targetPort: 5432 